### ISSUE TITLE
Japanese Text 

### ISSUE THREAD

**Issue by rzhbishal** [TobyChow/live-text-recognition#1]
Does this works with japanese text? I tried and it did not.

**Comment by TobyChow** [comment]
Nope, this uses [vision camera ocr](https://github.com/aarongrider/vision-camera-ocr) which is based on a Google's ML kit. You can try upgrading ML kit to version 2 which supports Japanese

**Comment by rzhbishal** [comment]
@TobyChow  i tried updating to v2 but it did not work at all. Could you help me out?
